name: openeatsjournal
description: "Free and open source eats, nutrition and calories journal"
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  graphic: ^2.6.0
  http: ^1.6.0
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.3
  sqflite_common_ffi: ^2.4.0+2
  mockito: ^5.6.3
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/